apiVersion: v1
kind: DeploymentConfig
metadata:
  name: example-httpd
  labels:
    app: example-httpd
    name: example-httpd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: example-httpd
    spec:
      containers:
      - name: example-httpd
        image: 172.30.1.1:5000/avl/example-httpd:v1.0
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:                 
        - mountPath: /usr/local/apache2/logs
          name: example-httpd-logs
      volumes:                          
        - name: example-httpd-logs
          emptyDir:
          medium: Memory          
---
apiVersion: v1
kind: Service
metadata:
  name: example-httpd
  labels:
    name: example-httpd
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    name: example-httpd
---
apiVersion: v1
kind: Route
metadata:
  name: example-httpd
spec:
  host: example-httpd.okd1.pipeline.avl
  to:
    kind: Service
    name: example-httpd



